export interface User {
  id: string;
  email: string;
  first_name: string;
  last_name: string;
  username?: string;
  phone?: string;
  profile_picture?: string;
  personal_code?: string;
  role?: 'CLIENT' | 'PROVIDER';
  active_role?: 'CLIENT' | 'PROVIDER';
  address?: Address;
  is_verified?: boolean;
  is_active?: boolean;
  credit_points?: number;
  jobs_done?: number;
  active_jobs?: number;
  rating?: number;
}

export interface Address {
  street?: string;
  city?: string;
  county?: string;
  postal_code?: string;
  country?: string;
  house_number?: string;
}

export interface AuthTokens {
  access_token: string;
  refresh_token: string;
  token_type: string;
}

export interface Category {
  id: string;
  name: string;
  iconLib: 'MaterialCommunityIcons' | 'Ionicons' | 'Feather';
  iconName: string;
  color: string;
}

export interface Provider {
  id: string;
  name: string;
  avatar?: string;
  rating?: number;
  reviewCount?: number;
  jobsDone?: number;
  badge?: number;
  credibility?: number;
  specialty?: string;
  location?: string;
  isOnline?: boolean;
}

export interface Service {
  id: string;
  title: string;
  category: string;
  categoryId: string;
  provider: Provider;
  price: number;
  rating: number;
  reviewCount: number;
  image: string;
  images?: string[];
  location: string;
  description?: string;
  isBookmarked?: boolean;
  avgPriceMin?: number;
  avgPriceMax?: number;
}

export type BookingStatus =
  | 'draft'
  | 'open'
  | 'shortlisted'
  | 'assigned'
  | 'arrived'
  | 'in_progress'
  | 'revision_requested'
  | 'completed'
  | 'approved'
  | 'closed'
  | 'cancelled'
  | 'disputed'
  | 'expired'
  | 'paused';

export interface Booking {
  id: string;
  service: Service;
  provider: Provider;
  status: BookingStatus;
  date: string;
  time: string;
  price: number;
  address?: string;
  description?: string;
  isUrgent?: boolean;
}

export interface Notification {
  id: string;
  title: string;
  message: string;
  type: 'booking' | 'offer' | 'review' | 'payment' | 'system';
  time: string;
  isRead: boolean;
}

export interface ChatMessage {
  id: string;
  text?: string;
  image?: string;
  voice?: string;
  voiceDuration?: number;
  sender: 'me' | 'other';
  timestamp: string;
  senderName?: string;
  senderAvatar?: string;
}

export interface ChatThread {
  id: string;
  participant: Provider;
  lastMessage: string;
  lastTime: string;
  unreadCount: number;
  jobTitle?: string;
}

export interface Offer {
  id: string;
  title: string;
  subtitle: string;
  discount: number;
  description?: string;
  bg: string;
  bgImage?: string;
}

export interface Review {
  id: string;
  reviewer: {
    name: string;
    avatar?: string;
  };
  rating: number;
  comment: string;
  date: string;
}

// ─── Ticketing (Module 10) ─────────────────────────────────────────────────
export type TicketCategory =
  | 'Payment Issue'
  | 'Job Dispute'
  | 'Cancellation Issue'
  | 'No-show'
  | 'Misconduct'
  | 'Technical Issue'
  | 'Account Verification'
  | 'Other';

export type TicketStatus = 'Open' | 'In Review' | 'Waiting' | 'Resolved' | 'Closed';

export interface Ticket {
  id: string; // SB-TKT-YYYY-NNNNNN
  createdAt: number;
  status: TicketStatus;
  category: TicketCategory;
  description: string;
  attachments: string[];
  userId: string;
  userName: string;
  userRole: 'CLIENT' | 'PROVIDER';
  jobId?: string;
  jobCategory?: string;
  jobDate?: string;
  assignedProviderName?: string;
  amount?: number;
  paymentStatus?: string;
  transactionId?: string;
  autoGenerated?: boolean;
}

// ─── Jobs & Bidding (Phase 2) ──────────────────────────────────────────────────
export type JobUrgency = 'urgent' | 'regular';
export type JobStatus =
  | 'draft'
  | 'bidding'
  | 'short_listed'
  | 'task_assigned'
  | 'pending_payment'
  | 'arrived'
  | 'in_progress'
  | 'revision_requested'
  | 'completed'
  | 'approved'
  | 'closed'
  | 'cancelled'
  | 'expired'
  | 'disputed'
  | 'paused';

export interface Job {
  id: string;
  clientId: string;
  clientName: string;
  title: string;
  description: string;
  categoryId: string;
  category: string;
  date: string;
  time: string;
  expectedHours: number;
  hourlyRate: number;
  expectedPrice: number;
  photos: string[];
  urgency: JobUrgency;
  status: JobStatus;
  biddingEndsAt: number;
  biddingDurationMs: number;
  location: string;
  assignedProviderId?: string;
  assignedPrice?: number; // final agreed price once a bid is accepted
  paymentDeadline?: number; // epoch ms — 10-minute payment window
  paymentMethod?: PaymentMethod;
  arrivedAt?: number;
  denialCount?: number; // client can deny up to 2 times
  revisionRequest?: RevisionRequest;
  cancellation?: CancellationInfo;
  disputeReason?: string;
  clientReview?: JobReview;
  providerReview?: JobReview;
}

export type PaymentMethod = 'card' | 'apple_pay' | 'google_pay' | 'bank_transfer' | 'credit_points';

export interface RevisionRequest {
  proposedBy: 'client' | 'provider';
  extraHours: number;
  newPrice: number;
  status: 'pending' | 'approved' | 'denied';
}

export interface CancellationInfo {
  by: 'client' | 'provider';
  reason: string;
  feeCharged?: number;
}

export interface JobReview {
  rating: number;
  comment?: string;
}

export interface OrderBreakdown {
  bidPrice: number;
  beforeVat: number;
  vat: number;
  platformFee: number;
  total: number;
}

export interface PayoutBreakdown {
  bidPrice: number;
  beforeVat: number;
  vat: number;
  platformFee: number;
  commission: number;
  payout: number;
}

export interface BidProvider extends Provider {
  distanceKm: number;
  responseTimeMin: number;
}

export interface Bid {
  id: string;
  jobId: string;
  provider: BidProvider;
  price: number;
  eta: string;
  createdAt: number;
  score: number;
}
