import type { Ticket, TicketCategory } from '@/types';
import { CURRENT_USER } from '@/data/mockData';

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 'SB-TKT-2026-000041',
    createdAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
    status: 'Resolved',
    category: 'Payment Issue',
    description: 'My card was charged twice for the same booking.',
    attachments: [],
    userId: CURRENT_USER.id,
    userName: CURRENT_USER.name,
    userRole: 'CLIENT',
  },
  {
    id: 'SB-TKT-2026-000058',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    status: 'In Review',
    category: 'Technical Issue',
    description: 'The app crashed while uploading photos to a job post.',
    attachments: [],
    userId: CURRENT_USER.id,
    userName: CURRENT_USER.name,
    userRole: 'CLIENT',
  },
];

let ticketCounter = 58;

export function generateTicketId(): string {
  ticketCounter += 1;
  const year = new Date().getFullYear();
  return `SB-TKT-${year}-${String(ticketCounter).padStart(6, '0')}`;
}

interface CreateTicketInput {
  category: TicketCategory;
  description: string;
  attachments?: string[];
  jobId?: string;
  jobCategory?: string;
  jobDate?: string;
  assignedProviderName?: string;
  amount?: number;
  paymentStatus?: string;
  transactionId?: string;
  autoGenerated?: boolean;
  userRole?: 'CLIENT' | 'PROVIDER';
}

export function createTicket(input: CreateTicketInput): Ticket {
  const ticket: Ticket = {
    id: generateTicketId(),
    createdAt: Date.now(),
    status: 'Open',
    category: input.category,
    description: input.description,
    attachments: input.attachments ?? [],
    userId: CURRENT_USER.id,
    userName: CURRENT_USER.name,
    userRole: input.userRole ?? 'CLIENT',
    jobId: input.jobId,
    jobCategory: input.jobCategory,
    jobDate: input.jobDate,
    assignedProviderName: input.assignedProviderName,
    amount: input.amount,
    paymentStatus: input.paymentStatus,
    transactionId: input.transactionId,
    autoGenerated: input.autoGenerated,
  };
  MOCK_TICKETS.unshift(ticket);
  return ticket;
}
