const palette = {
  primary: '#3A9E8F',
  primaryDark: '#2D7A6E',
  primaryLight: '#E8F5F3',
  rating: '#FFB800',
  destructive: '#E74C3C',
  destructiveForeground: '#FFFFFF',
  success: '#27AE60',
  successLight: '#E8F8EE',
  warning: '#F39C12',
};

const colors = {
  light: {
    text: '#1A1A1A',
    tint: palette.primary,
    background: '#F8F8F8',
    surface: '#FFFFFF',
    foreground: '#1A1A1A',
    card: '#FFFFFF',
    cardForeground: '#1A1A1A',
    primary: palette.primary,
    primaryForeground: '#FFFFFF',
    primaryLight: palette.primaryLight,
    primaryDark: palette.primaryDark,
    secondary: '#F5F5F5',
    secondaryForeground: '#1A1A1A',
    muted: '#F5F5F5',
    mutedForeground: '#737373',
    accent: palette.primaryLight,
    accentForeground: palette.primary,
    destructive: palette.destructive,
    destructiveForeground: palette.destructiveForeground,
    border: '#E8E8E8',
    input: '#F5F5F5',
    rating: palette.rating,
    urgent: palette.destructive,
    urgentLight: '#FFF0EF',
    success: palette.success,
    successLight: palette.successLight,
    warning: palette.warning,
    shadow: 'rgba(0, 0, 0, 0.08)',
    shadowMd: 'rgba(0, 0, 0, 0.12)',
    overlay: 'rgba(0, 0, 0, 0.5)',
    headerBg: palette.primary,
    tabBarActive: palette.primary,
    tabBarInactive: '#9E9E9E',
    tabBarBg: '#FFFFFF',
    skeletonBase: '#F0F0F0',
    skeletonHighlight: '#FAFAFA',
  },
  dark: {
    text: '#F0F0F0',
    tint: '#4DBFAD',
    background: '#111614',
    surface: '#1A211F',
    foreground: '#F0F0F0',
    card: '#1E2A27',
    cardForeground: '#F0F0F0',
    // Slightly brighter primary so it pops on dark surfaces
    primary: '#4DBFAD',
    primaryForeground: '#FFFFFF',
    primaryLight: 'rgba(77, 191, 173, 0.15)',
    primaryDark: palette.primary,
    secondary: '#1E2A27',
    secondaryForeground: '#F0F0F0',
    muted: '#1E2A27',
    mutedForeground: '#8A9E99',
    accent: 'rgba(58, 158, 143, 0.15)',
    accentForeground: '#4DBFAD',
    destructive: '#E74C3C',
    destructiveForeground: '#FFFFFF',
    border: '#2A3A37',
    input: '#1E2A27',
    rating: palette.rating,
    urgent: palette.destructive,
    urgentLight: 'rgba(231, 76, 60, 0.15)',
    success: palette.success,
    successLight: 'rgba(39, 174, 96, 0.15)',
    warning: palette.warning,
    shadow: 'rgba(0, 0, 0, 0.3)',
    shadowMd: 'rgba(0, 0, 0, 0.4)',
    overlay: 'rgba(0, 0, 0, 0.7)',
    headerBg: '#1A2E2B',
    tabBarActive: '#3ABFAD',
    tabBarInactive: '#5A7A75',
    tabBarBg: '#141F1D',
    skeletonBase: '#1E2A27',
    skeletonHighlight: '#253530',
  },
  radius: 12,
};

export default colors;
