const colors = {
  light: {
    text: '#1A1A1A',
    tint: '#3A9E8F',
    background: '#FFFFFF',
    foreground: '#1A1A1A',
    card: '#FFFFFF',
    cardForeground: '#1A1A1A',
    primary: '#3A9E8F',
    primaryForeground: '#FFFFFF',
    primaryLight: '#E8F5F3',
    primaryDark: '#2D7A6E',
    secondary: '#F5F5F5',
    secondaryForeground: '#1A1A1A',
    muted: '#F5F5F5',
    mutedForeground: '#737373',
    accent: '#E8F5F3',
    accentForeground: '#3A9E8F',
    destructive: '#E74C3C',
    destructiveForeground: '#FFFFFF',
    border: '#E8E8E8',
    input: '#F5F5F5',
    rating: '#FFB800',
    urgent: '#E74C3C',
    urgentLight: '#FFF0EF',
    success: '#27AE60',
    successLight: '#E8F8EE',
    warning: '#F39C12',
    shadow: 'rgba(0, 0, 0, 0.08)',
    shadowMd: 'rgba(0, 0, 0, 0.12)',
    overlay: 'rgba(0, 0, 0, 0.5)',
    headerBg: '#3A9E8F',
    tabBarActive: '#3A9E8F',
    tabBarInactive: '#9E9E9E',
    skeletonBase: '#F0F0F0',
    skeletonHighlight: '#FAFAFA',
  },
  radius: 12,
};

export default colors;
