import React from 'react';
import { FlatList, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useTheme } from '@/context/ThemeContext';
import { MOCK_TICKETS } from '@/data/ticketStore';
import BackButton from '@/components/BackButton';
import EmptyState from '@/components/EmptyState';
import type { TicketStatus } from '@/types';

const STATUS_COLOR: Record<TicketStatus, 'warning' | 'primary' | 'mutedForeground' | 'success' | 'destructive'> = {
  Open: 'warning',
  'In Review': 'primary',
  Waiting: 'mutedForeground',
  Resolved: 'success',
  Closed: 'destructive',
};

export default function MyTicketsScreen() {
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const { colors: c } = useTheme();

  return (
    <View style={[styles.root, { backgroundColor: c.background, paddingTop: insets.top }]}>
      <View style={[styles.header, { backgroundColor: c.surface, borderBottomColor: c.border }]}>
        <BackButton />
        <Text style={[styles.headerTitle, { color: c.text }]}>My Tickets</Text>
        <TouchableOpacity onPress={() => router.push('/profile/raise-ticket' as any)}>
          <Feather name="plus" size={22} color={c.primary} />
        </TouchableOpacity>
      </View>

      <FlatList
        data={MOCK_TICKETS}
        keyExtractor={(t) => t.id}
        contentContainerStyle={{ padding: 20, paddingBottom: 40, flexGrow: 1 }}
        ListEmptyComponent={
          <EmptyState icon="file-text" title="No tickets yet" subtitle="Tickets you raise with Support will show up here." />
        }
        renderItem={({ item }) => {
          const colorKey = STATUS_COLOR[item.status];
          return (
            <TouchableOpacity
              style={[styles.card, { backgroundColor: c.card, borderColor: c.border }]}
              onPress={() => router.push(`/profile/tickets/${item.id}` as any)}
            >
              <View style={styles.topRow}>
                <Text style={[styles.ticketId, { color: c.mutedForeground }]}>{item.id}</Text>
                <View style={[styles.statusChip, { backgroundColor: c[colorKey] + '22' }]}>
                  <Text style={[styles.statusText, { color: c[colorKey] }]}>{item.status}</Text>
                </View>
              </View>
              <Text style={[styles.category, { color: c.text }]}>{item.category}</Text>
              <Text style={[styles.desc, { color: c.mutedForeground }]} numberOfLines={2}>{item.description}</Text>
              {item.autoGenerated && (
                <View style={styles.autoTag}>
                  <Feather name="zap" size={10} color={c.mutedForeground} />
                  <Text style={[styles.autoTagText, { color: c.mutedForeground }]}>Auto-generated from dispute</Text>
                </View>
              )}
            </TouchableOpacity>
          );
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  header: { paddingHorizontal: 20, paddingVertical: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1 },
  headerTitle: { fontFamily: 'Manrope_700Bold', fontSize: 18 },
  card: { borderWidth: 1, borderRadius: 14, padding: 14, marginBottom: 12 },
  topRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 },
  ticketId: { fontFamily: 'Manrope_500Medium', fontSize: 11 },
  statusChip: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  statusText: { fontFamily: 'Manrope_600SemiBold', fontSize: 10 },
  category: { fontFamily: 'Manrope_700Bold', fontSize: 14, marginBottom: 4 },
  desc: { fontFamily: 'Manrope_400Regular', fontSize: 12, lineHeight: 17 },
  autoTag: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 8 },
  autoTagText: { fontFamily: 'Manrope_400Regular', fontSize: 10 },
});
