import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type LanguageCode = 'en' | 'de' | 'et' | 'lv' | 'lt';

const LANG_KEY = 'sb_language';

// Translation dictionary — currently covers the highest-visibility, most
// frequently seen strings (tab bar, Home headings, common actions) as a
// working foundation. Extending coverage to every string in the app is a
// large follow-up task (40+ screens) tracked separately.
const STRINGS: Record<LanguageCode, Record<string, string>> = {
  en: {
    tab_home: 'Home',
    tab_services: 'Services',
    tab_jobs: 'Jobs',
    tab_inbox: 'Inbox',
    tab_profile: 'Profile',
    home_heading: 'What service do you need today?',
    home_credit_points: 'Credit Points',
    home_earn_note: 'Earn 1 pt per €1 spent',
    home_categories: 'Categories',
    home_special_for_you: 'Special For You',
    home_why_skillbuddy: 'Why SkillBuddy?',
    home_earn_badges: 'Earn Badges',
    home_recommended: 'Recommended For You',
    home_popular_services: 'Popular Services',
    home_browse_services: 'Browse Services',
    home_my_bookings: 'My Bookings',
    home_chat: 'Chat',
    home_profile: 'Profile',
    see_all: 'See all',
    view_all: 'View All',
    search_placeholder: 'Search for a service...',
    post_a_job: 'Post a Job',
    book_now: 'Book Now',
    services_title: 'Services',
    services_get_custom_quote: 'Get a Custom Quote',
    services_start_live_chat: 'Start Live Chat',
    services_no_results: 'No services found',
    services_filter: 'Filter',
    jobs_title: 'Jobs',
    jobs_my_jobs: 'My Jobs',
    jobs_available: 'Available',
    jobs_my_bids: 'My Bids',
    jobs_active: 'Active Jobs',
    jobs_client_view: 'Client view',
    jobs_pilot_view: 'SkillBuddy Pilot view',
    jobs_switch_to_pilot: 'Switch to Pilot',
    jobs_switch_to_client: 'Switch to Client',
    jobs_no_jobs_client: 'No Jobs Posted Yet',
    jobs_no_jobs_provider: 'No Jobs Here Yet',
    inbox_title: 'Inbox',
    inbox_no_messages: 'No messages yet',
    profile_title: 'Profile',
    profile_personal_info: 'Personal Information',
    profile_professional_info: 'Professional Info',
    profile_documents: 'Documents',
    profile_credit_points: 'Credit Points',
    profile_wallet: 'Wallet & Payments',
    profile_settings: 'Settings',
    profile_dark_mode: 'Switch to Dark Mode',
    profile_light_mode: 'Switch to Light Mode',
    profile_support: 'Chat with Support',
    profile_safety: 'Safety & Help',
    profile_faqs: 'FAQs',
    profile_about: 'About Us',
    profile_privacy: 'Privacy & Cookie Policy',
    profile_terms: 'Terms & Conditions',
    profile_logout: 'Log Out',
    settings_title: 'Settings',
    settings_appearance: 'Appearance',
    settings_dark_mode: 'Dark Mode',
    settings_notifications: 'Notifications',
    settings_booking_updates: 'Booking Updates',
    settings_offers: 'Offers & Promotions',
    settings_chat_messages: 'Chat Messages',
    settings_language: 'Language',
    settings_account: 'Account',
    settings_change_password: 'Change Password',
    action_cancel: 'Cancel',
    action_save: 'Save',
    action_submit: 'Submit',
    action_apply: 'Apply',
    action_reset: 'Reset Filter',
    action_accept: 'Accept',
    action_view_profile: 'View Profile',
  },
  de: {
    tab_home: 'Start',
    tab_services: 'Dienste',
    tab_jobs: 'Aufträge',
    tab_inbox: 'Posteingang',
    tab_profile: 'Profil',
    home_heading: 'Welchen Service brauchst du heute?',
    home_credit_points: 'Punkte',
    home_earn_note: '1 Punkt pro €1 Ausgabe',
    home_categories: 'Kategorien',
    home_special_for_you: 'Nur für dich',
    home_why_skillbuddy: 'Warum SkillBuddy?',
    home_earn_badges: 'Abzeichen verdienen',
    home_recommended: 'Für dich empfohlen',
    home_popular_services: 'Beliebte Dienste',
    home_browse_services: 'Dienste durchsuchen',
    home_my_bookings: 'Meine Buchungen',
    home_chat: 'Chat',
    home_profile: 'Profil',
    see_all: 'Alle ansehen',
    view_all: 'Alle anzeigen',
    search_placeholder: 'Dienst suchen...',
    post_a_job: 'Auftrag erstellen',
    book_now: 'Jetzt buchen',
    services_title: 'Dienste',
    services_get_custom_quote: 'Individuelles Angebot',
    services_start_live_chat: 'Live-Chat starten',
    services_no_results: 'Keine Dienste gefunden',
    services_filter: 'Filter',
    jobs_title: 'Aufträge',
    jobs_my_jobs: 'Meine Aufträge',
    jobs_available: 'Verfügbar',
    jobs_my_bids: 'Meine Gebote',
    jobs_active: 'Aktive Aufträge',
    jobs_client_view: 'Kundenansicht',
    jobs_pilot_view: 'SkillBuddy-Pilot-Ansicht',
    jobs_switch_to_pilot: 'Zu Pilot wechseln',
    jobs_switch_to_client: 'Zu Kunde wechseln',
    jobs_no_jobs_client: 'Noch keine Aufträge erstellt',
    jobs_no_jobs_provider: 'Noch keine Aufträge hier',
    inbox_title: 'Posteingang',
    inbox_no_messages: 'Noch keine Nachrichten',
    profile_title: 'Profil',
    profile_personal_info: 'Persönliche Informationen',
    profile_professional_info: 'Berufliche Infos',
    profile_documents: 'Dokumente',
    profile_credit_points: 'Punkte',
    profile_wallet: 'Wallet & Zahlungen',
    profile_settings: 'Einstellungen',
    profile_dark_mode: 'Dunkelmodus aktivieren',
    profile_light_mode: 'Hellmodus aktivieren',
    profile_support: 'Support kontaktieren',
    profile_safety: 'Sicherheit & Hilfe',
    profile_faqs: 'FAQs',
    profile_about: 'Über uns',
    profile_privacy: 'Datenschutz & Cookies',
    profile_terms: 'AGB',
    profile_logout: 'Abmelden',
    settings_title: 'Einstellungen',
    settings_appearance: 'Erscheinungsbild',
    settings_dark_mode: 'Dunkelmodus',
    settings_notifications: 'Benachrichtigungen',
    settings_booking_updates: 'Buchungsupdates',
    settings_offers: 'Angebote & Aktionen',
    settings_chat_messages: 'Chat-Nachrichten',
    settings_language: 'Sprache',
    settings_account: 'Konto',
    settings_change_password: 'Passwort ändern',
    action_cancel: 'Abbrechen',
    action_save: 'Speichern',
    action_submit: 'Absenden',
    action_apply: 'Anwenden',
    action_reset: 'Filter zurücksetzen',
    action_accept: 'Annehmen',
    action_view_profile: 'Profil ansehen',
  },
  et: {
    tab_home: 'Avaleht',
    tab_services: 'Teenused',
    tab_jobs: 'Tööd',
    tab_inbox: 'Sõnumid',
    tab_profile: 'Profiil',
    home_heading: 'Millist teenust täna vajad?',
    home_credit_points: 'Krediidipunktid',
    home_earn_note: 'Teeni 1 punkt iga kulutatud €1 kohta',
    home_categories: 'Kategooriad',
    home_special_for_you: 'Just sinu jaoks',
    home_why_skillbuddy: 'Miks SkillBuddy?',
    home_earn_badges: 'Teeni märke',
    home_recommended: 'Soovitatud sinule',
    home_popular_services: 'Populaarsed teenused',
    home_browse_services: 'Sirvi teenuseid',
    home_my_bookings: 'Minu broneeringud',
    home_chat: 'Vestlus',
    home_profile: 'Profiil',
    see_all: 'Vaata kõiki',
    view_all: 'Vaata kõiki',
    search_placeholder: 'Otsi teenust...',
    post_a_job: 'Postita töö',
    book_now: 'Broneeri kohe',
    services_title: 'Teenused',
    services_get_custom_quote: 'Küsi pakkumist',
    services_start_live_chat: 'Alusta vestlust',
    services_no_results: 'Teenuseid ei leitud',
    services_filter: 'Filter',
    jobs_title: 'Tööd',
    jobs_my_jobs: 'Minu tööd',
    jobs_available: 'Saadaval',
    jobs_my_bids: 'Minu pakkumised',
    jobs_active: 'Aktiivsed tööd',
    jobs_client_view: 'Kliendi vaade',
    jobs_pilot_view: 'SkillBuddy Pilooti vaade',
    jobs_switch_to_pilot: 'Lülitu Piloodiks',
    jobs_switch_to_client: 'Lülitu Kliendiks',
    jobs_no_jobs_client: 'Töid pole veel postitatud',
    jobs_no_jobs_provider: 'Siin pole veel töid',
    inbox_title: 'Sõnumid',
    inbox_no_messages: 'Sõnumeid pole veel',
    profile_title: 'Profiil',
    profile_personal_info: 'Isikuandmed',
    profile_professional_info: 'Ametialane info',
    profile_documents: 'Dokumendid',
    profile_credit_points: 'Krediidipunktid',
    profile_wallet: 'Rahakott ja maksed',
    profile_settings: 'Seaded',
    profile_dark_mode: 'Lülitu tumedale režiimile',
    profile_light_mode: 'Lülitu heledale režiimile',
    profile_support: 'Vestle toega',
    profile_safety: 'Turvalisus ja abi',
    profile_faqs: 'KKK',
    profile_about: 'Meist',
    profile_privacy: 'Privaatsus ja küpsised',
    profile_terms: 'Tingimused',
    profile_logout: 'Logi välja',
    settings_title: 'Seaded',
    settings_appearance: 'Välimus',
    settings_dark_mode: 'Tume režiim',
    settings_notifications: 'Teated',
    settings_booking_updates: 'Broneeringu uuendused',
    settings_offers: 'Pakkumised ja kampaaniad',
    settings_chat_messages: 'Vestlussõnumid',
    settings_language: 'Keel',
    settings_account: 'Konto',
    settings_change_password: 'Muuda parooli',
    action_cancel: 'Tühista',
    action_save: 'Salvesta',
    action_submit: 'Esita',
    action_apply: 'Rakenda',
    action_reset: 'Lähtesta filter',
    action_accept: 'Nõustu',
    action_view_profile: 'Vaata profiili',
  },
  lv: {
    tab_home: 'Sākums',
    tab_services: 'Pakalpojumi',
    tab_jobs: 'Darbi',
    tab_inbox: 'Iesūtne',
    tab_profile: 'Profils',
    home_heading: 'Kāds pakalpojums šodien nepieciešams?',
    home_credit_points: 'Kredītpunkti',
    home_earn_note: 'Nopelni 1 punktu par katru iztērēto €1',
    home_categories: 'Kategorijas',
    home_special_for_you: 'Tieši jums',
    home_why_skillbuddy: 'Kāpēc SkillBuddy?',
    home_earn_badges: 'Nopelni nozīmītes',
    home_recommended: 'Ieteikts jums',
    home_popular_services: 'Populāri pakalpojumi',
    home_browse_services: 'Pārlūkot pakalpojumus',
    home_my_bookings: 'Manas rezervācijas',
    home_chat: 'Tērzēšana',
    home_profile: 'Profils',
    see_all: 'Skatīt visu',
    view_all: 'Skatīt visu',
    search_placeholder: 'Meklēt pakalpojumu...',
    post_a_job: 'Publicēt darbu',
    book_now: 'Rezervēt tagad',
    services_title: 'Pakalpojumi',
    services_get_custom_quote: 'Pieprasīt piedāvājumu',
    services_start_live_chat: 'Sākt tiešsaistes tērzēšanu',
    services_no_results: 'Pakalpojumi nav atrasti',
    services_filter: 'Filtrs',
    jobs_title: 'Darbi',
    jobs_my_jobs: 'Mani darbi',
    jobs_available: 'Pieejami',
    jobs_my_bids: 'Mani piedāvājumi',
    jobs_active: 'Aktīvie darbi',
    jobs_client_view: 'Klienta skats',
    jobs_pilot_view: 'SkillBuddy Pilota skats',
    jobs_switch_to_pilot: 'Pārslēgt uz Pilotu',
    jobs_switch_to_client: 'Pārslēgt uz Klientu',
    jobs_no_jobs_client: 'Vēl nav publicētu darbu',
    jobs_no_jobs_provider: 'Šeit vēl nav darbu',
    inbox_title: 'Iesūtne',
    inbox_no_messages: 'Vēl nav ziņojumu',
    profile_title: 'Profils',
    profile_personal_info: 'Personas informācija',
    profile_professional_info: 'Profesionālā informācija',
    profile_documents: 'Dokumenti',
    profile_credit_points: 'Kredītpunkti',
    profile_wallet: 'Maks un maksājumi',
    profile_settings: 'Iestatījumi',
    profile_dark_mode: 'Pārslēgt tumšo režīmu',
    profile_light_mode: 'Pārslēgt gaišo režīmu',
    profile_support: 'Sazināties ar atbalstu',
    profile_faqs: 'BUJ',
    profile_safety: 'Drošība un palīdzība',
    profile_about: 'Par mums',
    profile_privacy: 'Privātums un sīkfaili',
    profile_terms: 'Noteikumi',
    profile_logout: 'Izrakstīties',
    settings_title: 'Iestatījumi',
    settings_appearance: 'Izskats',
    settings_dark_mode: 'Tumšais režīms',
    settings_notifications: 'Paziņojumi',
    settings_booking_updates: 'Rezervāciju atjauninājumi',
    settings_offers: 'Piedāvājumi un akcijas',
    settings_chat_messages: 'Tērzēšanas ziņojumi',
    settings_language: 'Valoda',
    settings_account: 'Konts',
    settings_change_password: 'Mainīt paroli',
    action_cancel: 'Atcelt',
    action_save: 'Saglabāt',
    action_submit: 'Iesniegt',
    action_apply: 'Piemērot',
    action_reset: 'Atiestatīt filtru',
    action_accept: 'Pieņemt',
    action_view_profile: 'Skatīt profilu',
  },
  lt: {
    tab_home: 'Pradžia',
    tab_services: 'Paslaugos',
    tab_jobs: 'Darbai',
    tab_inbox: 'Gautieji',
    tab_profile: 'Profilis',
    home_heading: 'Kokios paslaugos jums reikia šiandien?',
    home_credit_points: 'Kredito taškai',
    home_earn_note: 'Uždirbkite 1 tašką už kiekvieną išleistą €1',
    home_categories: 'Kategorijos',
    home_special_for_you: 'Specialiai jums',
    home_why_skillbuddy: 'Kodėl SkillBuddy?',
    home_earn_badges: 'Uždirbkite ženkliukus',
    home_recommended: 'Rekomenduojama jums',
    home_popular_services: 'Populiarios paslaugos',
    home_browse_services: 'Naršyti paslaugas',
    home_my_bookings: 'Mano užsakymai',
    home_chat: 'Pokalbiai',
    home_profile: 'Profilis',
    see_all: 'Žiūrėti viską',
    view_all: 'Žiūrėti viską',
    search_placeholder: 'Ieškoti paslaugos...',
    post_a_job: 'Skelbti darbą',
    book_now: 'Rezervuoti dabar',
    services_title: 'Paslaugos',
    services_get_custom_quote: 'Gauti pasiūlymą',
    services_start_live_chat: 'Pradėti pokalbį',
    services_no_results: 'Paslaugų nerasta',
    services_filter: 'Filtras',
    jobs_title: 'Darbai',
    jobs_my_jobs: 'Mano darbai',
    jobs_available: 'Prieinami',
    jobs_my_bids: 'Mano pasiūlymai',
    jobs_active: 'Aktyvūs darbai',
    jobs_client_view: 'Kliento vaizdas',
    jobs_pilot_view: 'SkillBuddy Piloto vaizdas',
    jobs_switch_to_pilot: 'Perjungti į Pilotą',
    jobs_switch_to_client: 'Perjungti į Klientą',
    jobs_no_jobs_client: 'Dar nepaskelbta jokių darbų',
    jobs_no_jobs_provider: 'Čia dar nėra darbų',
    inbox_title: 'Gautieji',
    inbox_no_messages: 'Dar nėra žinučių',
    profile_title: 'Profilis',
    profile_personal_info: 'Asmeninė informacija',
    profile_professional_info: 'Profesinė informacija',
    profile_documents: 'Dokumentai',
    profile_credit_points: 'Kredito taškai',
    profile_wallet: 'Piniginė ir mokėjimai',
    profile_settings: 'Nustatymai',
    profile_dark_mode: 'Įjungti tamsų režimą',
    profile_light_mode: 'Įjungti šviesų režimą',
    profile_support: 'Kalbėtis su pagalba',
    profile_safety: 'Sauga ir pagalba',
    profile_faqs: 'DUK',
    profile_about: 'Apie mus',
    profile_privacy: 'Privatumas ir slapukai',
    profile_terms: 'Sąlygos',
    profile_logout: 'Atsijungti',
    settings_title: 'Nustatymai',
    settings_appearance: 'Išvaizda',
    settings_dark_mode: 'Tamsus režimas',
    settings_notifications: 'Pranešimai',
    settings_booking_updates: 'Užsakymų atnaujinimai',
    settings_offers: 'Pasiūlymai ir akcijos',
    settings_chat_messages: 'Pokalbių žinutės',
    settings_language: 'Kalba',
    settings_account: 'Paskyra',
    settings_change_password: 'Keisti slaptažodį',
    action_cancel: 'Atšaukti',
    action_save: 'Išsaugoti',
    action_submit: 'Pateikti',
    action_apply: 'Taikyti',
    action_reset: 'Atstatyti filtrą',
    action_accept: 'Priimti',
    action_view_profile: 'Žiūrėti profilį',
  },
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: keyof typeof STRINGS['en']) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => STRINGS.en[key] ?? key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY).then((saved) => {
      if (saved && saved in STRINGS) setLanguageState(saved as LanguageCode);
    });
  }, []);

  const setLanguage = useCallback((lang: LanguageCode) => {
    setLanguageState(lang);
    AsyncStorage.setItem(LANG_KEY, lang);
  }, []);

  const t = useCallback(
    (key: keyof typeof STRINGS['en']) => STRINGS[language][key] ?? STRINGS.en[key] ?? key,
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
