import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { useTheme } from '@/context/ThemeContext';
import { MOCK_TICKETS } from '@/data/ticketStore';
import BackButton from '@/components/BackButton';

const STATUS_STEPS = ['Open', 'In Review', 'Waiting', 'Resolved', 'Closed'] as const;

export default function TicketDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const { colors: c } = useTheme();

  const ticket = MOCK_TICKETS.find((t) => t.id === id);

  if (!ticket) {
    return (
      <View style={[styles.root, { backgroundColor: c.background, paddingTop: insets.top }]}>
        <Text style={{ color: c.text, padding: 20 }}>Ticket not found.</Text>
      </View>
    );
  }

  const stepIndex = STATUS_STEPS.indexOf(ticket.status);

  return (
    <View style={[styles.root, { backgroundColor: c.background, paddingTop: insets.top }]}>
      <View style={[styles.header, { backgroundColor: c.surface, borderBottomColor: c.border }]}>
        <BackButton />
        <Text style={[styles.headerTitle, { color: c.text }]}>{ticket.id}</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView contentContainerStyle={{ padding: 20, paddingBottom: 60 }} showsVerticalScrollIndicator={false}>
        {/* Status stepper */}
        <View style={styles.stepper}>
          {STATUS_STEPS.map((s, i) => (
            <View key={s} style={styles.stepItem}>
              <View style={[styles.stepDot, { backgroundColor: i <= stepIndex ? c.primary : c.muted }]} />
              <Text style={[styles.stepLabel, { color: i <= stepIndex ? c.primary : c.mutedForeground }]}>{s}</Text>
            </View>
          ))}
        </View>

        <View style={[styles.card, { backgroundColor: c.card, borderColor: c.border }]}>
          <Text style={[styles.category, { color: c.text }]}>{ticket.category}</Text>
          <Text style={[styles.desc, { color: c.mutedForeground }]}>{ticket.description}</Text>

          {ticket.jobId && (
            <View style={[styles.fieldBlock, { borderTopColor: c.border }]}>
              <Text style={[styles.fieldLabel, { color: c.mutedForeground }]}>Related Job</Text>
              <Text style={[styles.fieldValue, { color: c.text }]}>
                {ticket.jobCategory} {ticket.jobDate ? `— ${ticket.jobDate}` : ''}
              </Text>
            </View>
          )}
          {ticket.amount !== undefined && (
            <View style={[styles.fieldBlock, { borderTopColor: c.border }]}>
              <Text style={[styles.fieldLabel, { color: c.mutedForeground }]}>Amount</Text>
              <Text style={[styles.fieldValue, { color: c.text }]}>€{ticket.amount.toFixed(2)}</Text>
            </View>
          )}
          <View style={[styles.fieldBlock, { borderTopColor: c.border }]}>
            <Text style={[styles.fieldLabel, { color: c.mutedForeground }]}>Submitted by</Text>
            <Text style={[styles.fieldValue, { color: c.text }]}>{ticket.userName} ({ticket.userRole})</Text>
          </View>
          <View style={[styles.fieldBlock, { borderTopColor: c.border }]}>
            <Text style={[styles.fieldLabel, { color: c.mutedForeground }]}>Created</Text>
            <Text style={[styles.fieldValue, { color: c.text }]}>{new Date(ticket.createdAt).toLocaleDateString()}</Text>
          </View>
          {ticket.autoGenerated && (
            <View style={styles.autoNote}>
              <Feather name="zap" size={12} color={c.mutedForeground} />
              <Text style={[styles.autoNoteText, { color: c.mutedForeground }]}>Auto-generated from a job dispute</Text>
            </View>
          )}
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1 },
  header: { paddingHorizontal: 20, paddingVertical: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1 },
  headerTitle: { fontFamily: 'Manrope_700Bold', fontSize: 16 },
  stepper: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  stepItem: { alignItems: 'center', flex: 1 },
  stepDot: { width: 12, height: 12, borderRadius: 6, marginBottom: 6 },
  stepLabel: { fontFamily: 'Manrope_500Medium', fontSize: 9, textAlign: 'center' },
  card: { borderWidth: 1, borderRadius: 16, padding: 18 },
  category: { fontFamily: 'Manrope_700Bold', fontSize: 17, marginBottom: 8 },
  desc: { fontFamily: 'Manrope_400Regular', fontSize: 14, lineHeight: 21 },
  fieldBlock: { borderTopWidth: 1, paddingTop: 12, marginTop: 12 },
  fieldLabel: { fontFamily: 'Manrope_500Medium', fontSize: 11 },
  fieldValue: { fontFamily: 'Manrope_600SemiBold', fontSize: 14, marginTop: 3 },
  autoNote: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 16 },
  autoNoteText: { fontFamily: 'Manrope_400Regular', fontSize: 11 },
});
